"""add_users_table_and_workflow_user_id

Revision ID: b0f8c8310273
Revises: de336a17b7e1
Create Date: 2026-07-26 23:30:44.752207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b0f8c8310273'
down_revision: Union[str, Sequence[str], None] = 'de336a17b7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_column('workflows', 'user_id')
    # ### end Alembic commands ###
