// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CredentialCreate
 */
export type CredentialCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Service Type
     */
    service_type: string;
    /**
     * Raw Secret
     */
    raw_secret: string;
};

/**
 * CredentialRead
 */
export type CredentialRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Service Type
     */
    service_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CustomToolCreate
 */
export type CustomToolCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    tool_type?: ToolType;
    /**
     * Code Or Url
     */
    code_or_url: string;
    /**
     * Input Schema
     */
    input_schema?: {
        [key: string]: unknown;
    };
    /**
     * Output Schema
     */
    output_schema?: {
        [key: string]: unknown;
    };
};

/**
 * CustomToolRead
 */
export type CustomToolRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    tool_type?: ToolType;
    /**
     * Code Or Url
     */
    code_or_url: string;
    /**
     * Input Schema
     */
    input_schema?: {
        [key: string]: unknown;
    };
    /**
     * Output Schema
     */
    output_schema?: {
        [key: string]: unknown;
    };
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ExecutionStatus
 */
export type ExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * StepLogRead
 */
export type StepLogRead = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Node Name
     */
    node_name: string;
    /**
     * Node Type
     */
    node_type: string;
    status?: ExecutionStatus;
    /**
     * Input Data
     */
    input_data?: {
        [key: string]: unknown;
    };
    /**
     * Output Data
     */
    output_data?: {
        [key: string]: unknown;
    };
    /**
     * Thought Trace
     */
    thought_trace?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * ToolType
 */
export type ToolType = 'python_code' | 'http_api' | 'builtin';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowCreate
 */
export type WorkflowCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Nodes
     */
    nodes?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Edges
     */
    edges?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * WorkflowRead
 */
export type WorkflowRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Nodes
     */
    nodes?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Edges
     */
    edges?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowRunRead
 */
export type WorkflowRunRead = {
    /**
     * Workflow Id
     */
    workflow_id: string;
    status?: ExecutionStatus;
    /**
     * Trigger Type
     */
    trigger_type?: string;
    /**
     * Input Data
     */
    input_data?: {
        [key: string]: unknown;
    };
    /**
     * Output Data
     */
    output_data?: {
        [key: string]: unknown;
    };
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at?: string | null;
};

/**
 * WorkflowUpdate
 */
export type WorkflowUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Nodes
     */
    nodes?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Edges
     */
    edges?: Array<{
        [key: string]: unknown;
    }> | null;
};

export type ListWorkflowsApiV1WorkflowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workflows/';
};

export type ListWorkflowsApiV1WorkflowsGetResponses = {
    /**
     * Response List Workflows Api V1 Workflows  Get
     *
     * Successful Response
     */
    200: Array<WorkflowRead>;
};

export type ListWorkflowsApiV1WorkflowsGetResponse = ListWorkflowsApiV1WorkflowsGetResponses[keyof ListWorkflowsApiV1WorkflowsGetResponses];

export type CreateWorkflowApiV1WorkflowsPostData = {
    body: WorkflowCreate;
    path?: never;
    query?: never;
    url: '/api/v1/workflows/';
};

export type CreateWorkflowApiV1WorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowApiV1WorkflowsPostError = CreateWorkflowApiV1WorkflowsPostErrors[keyof CreateWorkflowApiV1WorkflowsPostErrors];

export type CreateWorkflowApiV1WorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: WorkflowRead;
};

export type CreateWorkflowApiV1WorkflowsPostResponse = CreateWorkflowApiV1WorkflowsPostResponses[keyof CreateWorkflowApiV1WorkflowsPostResponses];

export type DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteError = DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteResponse = DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteResponses[keyof DeleteWorkflowApiV1WorkflowsWorkflowIdDeleteResponses];

export type GetWorkflowApiV1WorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type GetWorkflowApiV1WorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowApiV1WorkflowsWorkflowIdGetError = GetWorkflowApiV1WorkflowsWorkflowIdGetErrors[keyof GetWorkflowApiV1WorkflowsWorkflowIdGetErrors];

export type GetWorkflowApiV1WorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRead;
};

export type GetWorkflowApiV1WorkflowsWorkflowIdGetResponse = GetWorkflowApiV1WorkflowsWorkflowIdGetResponses[keyof GetWorkflowApiV1WorkflowsWorkflowIdGetResponses];

export type UpdateWorkflowApiV1WorkflowsWorkflowIdPutData = {
    body: WorkflowUpdate;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type UpdateWorkflowApiV1WorkflowsWorkflowIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowApiV1WorkflowsWorkflowIdPutError = UpdateWorkflowApiV1WorkflowsWorkflowIdPutErrors[keyof UpdateWorkflowApiV1WorkflowsWorkflowIdPutErrors];

export type UpdateWorkflowApiV1WorkflowsWorkflowIdPutResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRead;
};

export type UpdateWorkflowApiV1WorkflowsWorkflowIdPutResponse = UpdateWorkflowApiV1WorkflowsWorkflowIdPutResponses[keyof UpdateWorkflowApiV1WorkflowsWorkflowIdPutResponses];

export type ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostData = {
    /**
     * Payload
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/execute';
};

export type ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostError = ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostErrors[keyof ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostErrors];

export type ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRunRead;
};

export type ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostResponse = ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostResponses[keyof ExecuteWorkflowApiV1WorkflowsWorkflowIdExecutePostResponses];

export type ListExecutionsApiV1ExecutionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Workflow Id
         */
        workflow_id?: string;
    };
    url: '/api/v1/executions/';
};

export type ListExecutionsApiV1ExecutionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExecutionsApiV1ExecutionsGetError = ListExecutionsApiV1ExecutionsGetErrors[keyof ListExecutionsApiV1ExecutionsGetErrors];

export type ListExecutionsApiV1ExecutionsGetResponses = {
    /**
     * Response List Executions Api V1 Executions  Get
     *
     * Successful Response
     */
    200: Array<WorkflowRunRead>;
};

export type ListExecutionsApiV1ExecutionsGetResponse = ListExecutionsApiV1ExecutionsGetResponses[keyof ListExecutionsApiV1ExecutionsGetResponses];

export type GetExecutionRunApiV1ExecutionsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/executions/{run_id}';
};

export type GetExecutionRunApiV1ExecutionsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionRunApiV1ExecutionsRunIdGetError = GetExecutionRunApiV1ExecutionsRunIdGetErrors[keyof GetExecutionRunApiV1ExecutionsRunIdGetErrors];

export type GetExecutionRunApiV1ExecutionsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRunRead;
};

export type GetExecutionRunApiV1ExecutionsRunIdGetResponse = GetExecutionRunApiV1ExecutionsRunIdGetResponses[keyof GetExecutionRunApiV1ExecutionsRunIdGetResponses];

export type GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/executions/{run_id}/logs';
};

export type GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetError = GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetErrors[keyof GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetErrors];

export type GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetResponses = {
    /**
     * Response Get Execution Step Logs Api V1 Executions  Run Id  Logs Get
     *
     * Successful Response
     */
    200: Array<StepLogRead>;
};

export type GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetResponse = GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetResponses[keyof GetExecutionStepLogsApiV1ExecutionsRunIdLogsGetResponses];

export type CancelExecutionRunApiV1ExecutionsRunIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/executions/{run_id}/cancel';
};

export type CancelExecutionRunApiV1ExecutionsRunIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelExecutionRunApiV1ExecutionsRunIdCancelPostError = CancelExecutionRunApiV1ExecutionsRunIdCancelPostErrors[keyof CancelExecutionRunApiV1ExecutionsRunIdCancelPostErrors];

export type CancelExecutionRunApiV1ExecutionsRunIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRunRead;
};

export type CancelExecutionRunApiV1ExecutionsRunIdCancelPostResponse = CancelExecutionRunApiV1ExecutionsRunIdCancelPostResponses[keyof CancelExecutionRunApiV1ExecutionsRunIdCancelPostResponses];

export type ListCredentialsApiV1CredentialsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/credentials/';
};

export type ListCredentialsApiV1CredentialsGetResponses = {
    /**
     * Response List Credentials Api V1 Credentials  Get
     *
     * Successful Response
     */
    200: Array<CredentialRead>;
};

export type ListCredentialsApiV1CredentialsGetResponse = ListCredentialsApiV1CredentialsGetResponses[keyof ListCredentialsApiV1CredentialsGetResponses];

export type CreateCredentialApiV1CredentialsPostData = {
    body: CredentialCreate;
    path?: never;
    query?: never;
    url: '/api/v1/credentials/';
};

export type CreateCredentialApiV1CredentialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCredentialApiV1CredentialsPostError = CreateCredentialApiV1CredentialsPostErrors[keyof CreateCredentialApiV1CredentialsPostErrors];

export type CreateCredentialApiV1CredentialsPostResponses = {
    /**
     * Successful Response
     */
    201: CredentialRead;
};

export type CreateCredentialApiV1CredentialsPostResponse = CreateCredentialApiV1CredentialsPostResponses[keyof CreateCredentialApiV1CredentialsPostResponses];

export type DeleteCredentialApiV1CredentialsCredentialIdDeleteData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: string;
    };
    query?: never;
    url: '/api/v1/credentials/{credential_id}';
};

export type DeleteCredentialApiV1CredentialsCredentialIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCredentialApiV1CredentialsCredentialIdDeleteError = DeleteCredentialApiV1CredentialsCredentialIdDeleteErrors[keyof DeleteCredentialApiV1CredentialsCredentialIdDeleteErrors];

export type DeleteCredentialApiV1CredentialsCredentialIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCredentialApiV1CredentialsCredentialIdDeleteResponse = DeleteCredentialApiV1CredentialsCredentialIdDeleteResponses[keyof DeleteCredentialApiV1CredentialsCredentialIdDeleteResponses];

export type GetBuiltinToolsApiV1ToolsBuiltinGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools/builtin';
};

export type GetBuiltinToolsApiV1ToolsBuiltinGetResponses = {
    /**
     * Response Get Builtin Tools Api V1 Tools Builtin Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetBuiltinToolsApiV1ToolsBuiltinGetResponse = GetBuiltinToolsApiV1ToolsBuiltinGetResponses[keyof GetBuiltinToolsApiV1ToolsBuiltinGetResponses];

export type ListCustomToolsApiV1ToolsCustomGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools/custom';
};

export type ListCustomToolsApiV1ToolsCustomGetResponses = {
    /**
     * Response List Custom Tools Api V1 Tools Custom Get
     *
     * Successful Response
     */
    200: Array<CustomToolRead>;
};

export type ListCustomToolsApiV1ToolsCustomGetResponse = ListCustomToolsApiV1ToolsCustomGetResponses[keyof ListCustomToolsApiV1ToolsCustomGetResponses];

export type CreateCustomToolApiV1ToolsCustomPostData = {
    body: CustomToolCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tools/custom';
};

export type CreateCustomToolApiV1ToolsCustomPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomToolApiV1ToolsCustomPostError = CreateCustomToolApiV1ToolsCustomPostErrors[keyof CreateCustomToolApiV1ToolsCustomPostErrors];

export type CreateCustomToolApiV1ToolsCustomPostResponses = {
    /**
     * Successful Response
     */
    201: CustomToolRead;
};

export type CreateCustomToolApiV1ToolsCustomPostResponse = CreateCustomToolApiV1ToolsCustomPostResponses[keyof CreateCustomToolApiV1ToolsCustomPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
